server {
    listen 80 default_server;
    server_name metrigo.ru www.metrigo.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://metrigo.ru$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name metrigo.ru www.metrigo.ru;

    ssl_certificate /etc/letsencrypt/live/metrigo.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/metrigo.ru/privkey.pem;

    location / {
        return 200 'metrigo web placeholder';
        add_header Content-Type text/plain;
    }

    location /api/ {
        proxy_pass http://api:8000/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}