version = 5.5.0
archive_dir = /etc/letsencrypt/archive/metrigo.ru
cert = /etc/letsencrypt/live/metrigo.ru/cert.pem
privkey = /etc/letsencrypt/live/metrigo.ru/privkey.pem
chain = /etc/letsencrypt/live/metrigo.ru/chain.pem
fullchain = /etc/letsencrypt/live/metrigo.ru/fullchain.pem
[renewalparams]
account = 5193c7d5315af46e46f1759f58ce34d9
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
metrigo.ru = /var/www/certbot
